"""Add user_chat and user_settings tables

Revision ID: 8e4c442948bf
Revises: bc2290d11bb6
Create Date: 2026-04-20 11:07:19.591550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e4c442948bf'
down_revision: Union[str, Sequence[str], None] = 'bc2290d11bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('chat_id', sa.String(length=255), nullable=False),
    sa.Column('chat_title', sa.String(length=255), nullable=True),
    sa.Column('selected', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_chat_unique', 'user_chats', ['user_id', 'chat_id'], unique=True)
    op.create_index('idx_user_selected', 'user_chats', ['user_id', 'selected'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('selected_chat_id', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    op.drop_index('idx_user_selected', table_name='user_chats')
    op.drop_index('idx_user_chat_unique', table_name='user_chats')
    op.drop_table('user_chats')
    # ### end Alembic commands ###
