"""add Analysus Task

Revision ID: 9cdb6976c7f0
Revises: f6fc6e132746
Create Date: 2026-05-01 09:37:47.214537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cdb6976c7f0'
down_revision: Union[str, Sequence[str], None] = 'f6fc6e132746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('analysis_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.Enum('review', 'compliance', name='tasktype'), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('date_start', sa.String(length=50), nullable=True),
    sa.Column('date_end', sa.String(length=50), nullable=True),
    sa.Column('is_notified', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='taskstatus'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_tasks_chat_id'), 'analysis_tasks', ['chat_id'], unique=False)
    op.create_index(op.f('ix_analysis_tasks_is_notified'), 'analysis_tasks', ['is_notified'], unique=False)
    op.create_index(op.f('ix_analysis_tasks_status'), 'analysis_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_analysis_tasks_task_id'), 'analysis_tasks', ['task_id'], unique=True)
    op.create_index(op.f('ix_analysis_tasks_user_id'), 'analysis_tasks', ['user_id'], unique=False)
    op.create_index('ix_tasks_created', 'analysis_tasks', ['created_at'], unique=False)
    op.create_index('ix_tasks_user_status', 'analysis_tasks', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_user_status', table_name='analysis_tasks')
    op.drop_index('ix_tasks_created', table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_user_id'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_task_id'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_status'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_is_notified'), table_name='analysis_tasks')
    op.drop_index(op.f('ix_analysis_tasks_chat_id'), table_name='analysis_tasks')
    op.drop_table('analysis_tasks')
    # ### end Alembic commands ###
