"""Add reply_to_message_id

Revision ID: bc2290d11bb6
Revises: 69661d14daea
Create Date: 2026-04-19 17:36:44.456176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2290d11bb6'
down_revision: Union[str, Sequence[str], None] = '69661d14daea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to_message_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'reply_to_message_id')
    # ### end Alembic commands ###
