"""add index to db models

Revision ID: f6fc6e132746
Revises: 9a8bd1067698
Create Date: 2026-04-27 00:23:04.237089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6fc6e132746'
down_revision: Union[str, Sequence[str], None] = '9a8bd1067698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_reports_chat_id_created_at', 'analysis_reports', ['chat_id', 'created_at'], unique=False)
    op.create_index('idx_reports_chat_type_created', 'analysis_reports', ['chat_id', 'report_type', 'created_at'], unique=False)
    op.create_index('idx_reports_created_at', 'analysis_reports', ['created_at'], unique=False)
    op.create_index('idx_reports_date_range', 'analysis_reports', ['chat_id', 'date_range_start', 'date_range_end'], unique=False)
    op.create_index('idx_reports_report_type_chat_id', 'analysis_reports', ['report_type', 'chat_id'], unique=False)
    op.create_index('idx_chunks_chat_id_message_id', 'message_chunks', ['chat_id', 'message_id'], unique=False)
    op.create_index('idx_chunks_chat_id_timestamp', 'message_chunks', ['chat_id', 'timestamp'], unique=False)
    op.create_index('idx_chunks_covering', 'message_chunks', ['chat_id', 'timestamp', 'message_id'], unique=False)
    op.create_index('idx_chunks_embedding_ivfflat', 'message_chunks', ['embedding'], unique=False, postgresql_using='ivfflat')
    op.create_index('idx_chunks_message_id', 'message_chunks', ['message_id'], unique=False)
    op.create_index('idx_chunks_timestamp', 'message_chunks', ['timestamp'], unique=False)
    op.create_index('idx_msg_embeddings_created_at', 'message_embeddings', ['created_at'], unique=False)
    op.create_index('idx_msg_embeddings_embedding_ivfflat', 'message_embeddings', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_msg_embeddings_message_id', 'message_embeddings', ['message_id'], unique=False)
    op.create_index('idx_messages_chat_id_sender_id', 'messages', ['chat_id', 'sender_id'], unique=False)
    op.create_index('idx_messages_chat_id_timestamp', 'messages', ['chat_id', 'timestamp'], unique=False)
    op.create_index('idx_messages_content_gin', 'messages', ['content'], unique=False, postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.create_index('idx_messages_sender_id', 'messages', ['sender_id'], unique=False)
    op.create_index('idx_messages_timestamp', 'messages', ['timestamp'], unique=False)
    op.create_unique_constraint('uq_message_chat_message', 'messages', ['chat_id', 'message_id'])
    op.drop_index(op.f('idx_user_chat_unique'), table_name='user_chats')
    op.drop_index(op.f('idx_user_selected'), table_name='user_chats')
    op.create_index('idx_user_chats_chat_id', 'user_chats', ['chat_id'], unique=False)
    op.create_index('idx_user_chats_selected_idx', 'user_chats', ['selected'], unique=False)
    op.create_index('idx_user_chats_user_id_last_used', 'user_chats', ['user_id', 'last_used'], unique=False)
    op.create_index('idx_user_chats_user_id_selected', 'user_chats', ['user_id', 'selected'], unique=False)
    op.create_index('idx_user_chats_user_lastused', 'user_chats', ['user_id', 'last_used'], unique=False)
    op.create_unique_constraint('uq_user_chat_unique', 'user_chats', ['user_id', 'chat_id'])
    op.create_index('idx_user_settings_selected_chat', 'user_settings', ['selected_chat_id'], unique=False)
    op.create_index('idx_user_settings_updated', 'user_settings', ['updated_at'], unique=False)
    op.create_index('idx_user_settings_user_id', 'user_settings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_settings_user_id', table_name='user_settings')
    op.drop_index('idx_user_settings_updated', table_name='user_settings')
    op.drop_index('idx_user_settings_selected_chat', table_name='user_settings')
    op.drop_constraint('uq_user_chat_unique', 'user_chats', type_='unique')
    op.drop_index('idx_user_chats_user_lastused', table_name='user_chats')
    op.drop_index('idx_user_chats_user_id_selected', table_name='user_chats')
    op.drop_index('idx_user_chats_user_id_last_used', table_name='user_chats')
    op.drop_index('idx_user_chats_selected_idx', table_name='user_chats')
    op.drop_index('idx_user_chats_chat_id', table_name='user_chats')
    op.create_index(op.f('idx_user_selected'), 'user_chats', ['user_id', 'selected'], unique=False)
    op.create_index(op.f('idx_user_chat_unique'), 'user_chats', ['user_id', 'chat_id'], unique=True)
    op.drop_constraint('uq_message_chat_message', 'messages', type_='unique')
    op.drop_index('idx_messages_timestamp', table_name='messages')
    op.drop_index('idx_messages_sender_id', table_name='messages')
    op.drop_index('idx_messages_content_gin', table_name='messages', postgresql_using='gin', postgresql_ops={'content': 'gin_trgm_ops'})
    op.drop_index('idx_messages_chat_id_timestamp', table_name='messages')
    op.drop_index('idx_messages_chat_id_sender_id', table_name='messages')
    op.drop_index('idx_msg_embeddings_message_id', table_name='message_embeddings')
    op.drop_index('idx_msg_embeddings_embedding_ivfflat', table_name='message_embeddings', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_msg_embeddings_created_at', table_name='message_embeddings')
    op.drop_index('idx_chunks_timestamp', table_name='message_chunks')
    op.drop_index('idx_chunks_message_id', table_name='message_chunks')
    op.drop_index('idx_chunks_embedding_ivfflat', table_name='message_chunks', postgresql_using='ivfflat')
    op.drop_index('idx_chunks_covering', table_name='message_chunks')
    op.drop_index('idx_chunks_chat_id_timestamp', table_name='message_chunks')
    op.drop_index('idx_chunks_chat_id_message_id', table_name='message_chunks')
    op.drop_index('idx_reports_report_type_chat_id', table_name='analysis_reports')
    op.drop_index('idx_reports_date_range', table_name='analysis_reports')
    op.drop_index('idx_reports_created_at', table_name='analysis_reports')
    op.drop_index('idx_reports_chat_type_created', table_name='analysis_reports')
    op.drop_index('idx_reports_chat_id_created_at', table_name='analysis_reports')
    # ### end Alembic commands ###
